### ISSUE TITLE
microbot_microbot_1 exited with code 139

### ISSUE THREAD

**Issue by jamiehaywood** [containerize-my-server/reverse-proxy#10]
After running docker-compose up for the microbot docker-compose.yml, it pulled the image and came with this output on the CLI:

> 
microbot_1  | asmttpd - 0.3
microbot_1  | 
microbot_1  | Using Document Root: /var/www
microbot_1  | asmttpd - 0.3
microbot_1  | 
microbot_1  | Using Document Root: /var/www
microbot_1  | asmttpd - 0.3
microbot_1  | 
microbot_1  | Using Document Root: /var/www
microbot_1  | asmttpd - 0.3
microbot_1  | 
microbot_1  | Using Document Root: /var/www
microbot_1  | asmttpd - 0.3
microbot_1  | 
microbot_1  | Using Document Root: /var/www
microbot_1  | asmttpd - 0.3
microbot_1  | 
microbot_1  | Using Document Root: /var/www
microbot_1  | asmttpd - 0.3
microbot_1  | 
microbot_1  | Using Document Root: /var/www
microbot_1  | asmttpd - 0.3
microbot_1  | 
microbot_1  | Using Document Root: /var/www
microbot_1  | asmttpd - 0.3
microbot_1  | 
microbot_1  | Using Document Root: /var/www
microbot_1  | asmttpd - 0.3
microbot_1  | 
microbot_1  | Using Document Root: /var/www
microbot_microbot_1 exited with code 139

**Comment by vegasbrianc** [comment]
Hi @jamiehaywood Can you provide your environment information? What OS, Swarm Yes/No, config changes, etc? Thanks!

**Comment by jamiehaywood** [comment]
Thanks very much for taking the time to have a look at this. I was looking to experiment with Traefik, and came across your repo.

Ubuntu 16.04 - clean install. No swarming. No config changes from default.  

Followed your README.md instructions to a tee, got that output from the CLI.

**Comment by vegasbrianc** [comment]
Try this config. I am running this in production. This should work with either Swarm or compose

```
version: "3.4"

services:
  traefik:
    image: traefik:latest
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - my_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      - ./root/projects/traefik/traefik-config/:/etc/traefik/traefik.toml
      - /tmp/traefik.toml:/etc/traefik/
      - /tmp/acme.json:/acme.json
   # environment:
   #   - DO_AUTH_TOKEN=f9c010f57363e8f819ccd0c852706bde71fe740ffefad06d331e4159bf18aa9c
    command:
      - --debug=true
      - --logLevel=WARN
#      - --api
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
volumes:
    traefik_data: {}

networks:
  my_net:

```
